# Generated by Django 5.1.2 on 2024-10-22 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
