# Generated by Django 5.1.2 on 2024-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_booking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/packages/'),
        ),
    ]
